#!/usr/bin/env bash
# Configures Nginx to return the server hostname in an X-Served-By header.
# shellcheck disable=SC2154
apt-get update -y
apt-get install -y nginx

mkdir -p /var/www/html
printf '%s\n' "Holberton School for the win!" > /var/www/html/index.html

sed -i '/add_header X-Served-By/d' \
    /etc/nginx/sites-available/default

sed -i "/server_name _;/a \    add_header X-Served-By $HOSTNAME;" \
    /etc/nginx/sites-available/default

nginx -t
service nginx restart
