#!/usr/bin/env bash
# Installs HAProxy and distributes HTTP requests between two web servers.
set -e

apt-get update
apt-get -y install haproxy

printf '%s\n' "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 7139-web-01 44.201.123.60:80 check
    server 7139-web-02 18.233.154.155:80 check
HAPROXY

haproxy -c -f /etc/haproxy/haproxy.cfg
service haproxy restart
