#!/usr/bin/env bash
# Runs Nginx on port 80 while init reports that Nginx is not running.
ln -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
rm -f /run/nginx.pid
